# Book settings
title: My sample book
author: The Jupyter Book Community
logo: 'logo.png'

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

latex:
  latex_documents:
    targetname: book.tex
